name: githubaction-cd 

on:
  push:
    branches: [ "main" ] # "main" 브런치에 "push" 시 실행. (event)

jobs:
  cd:
    name : gitaction-cd
    runs-on: ubuntu-latest # github-action을 실행하기 위한 컴퓨터

    steps:
    - name : checkout
      uses: actions/checkout@v3 # 레포지토리 최신 버전의 코드를 가져오는 라이브러리. 

    - id : "auth"
      name : Authenticate to GCP
      uses : google-github-actions/auth@v0 # GCP인증을 위한 라이브러리.
      with:
        credentials_json: ${{ secrets.PRIVATE_KEY }} 
    
    - name : server-on
      run : |-
        gcloud compute ssh --project=${{ secrets.PROJECT_ID }} --zone=${{ secrets.GCP_ZONE }} ${{ secrets.USENAME }}@${{ secrets.GCP_INSTANCE_NAME }} -- \
        "cd github-action && \
        docker-compose stop && \
        docker system prune -a && \
        git pull && \
        docker-compose -f docker-compose.prod.yaml build && \
        docker-compose -f docker-compose.prod.yaml up -d
        "
        
